#!/bin/bash
declare -A display_settings

# Capure current display configuration
displays=$( xrandr | sed '/^\s\+/d' | tail -n +2 | grep " connected" | awk '{print $1}')
for display in $displays; do
    configuration=$(xrandr | grep "^$display" | sed -ne 's/.*\s\([0-9]\+x[0-9]\+.*\s\).*(.*/\1/p')
    display_settings[$display]=$configuration
done

# Run the command
$@

# Apply old display configuration
full_config=""
for key in ${!display_settings[@]}; do
    value=${display_settings["${key}"]}
    resolution=$(echo $value | sed 's/+.*//g')
    offset=$(echo $value | sed 's/[0-9]\+x[0-9]\++//' | sed 's/+/x/')

    full_config="$full_config --output $key --mode $resolution --pos $offset"

    echo "Restoring resolution: $resolution $offset"
done

xrandr $full_config
